services:
  - type: web
    name: instagram-bot-ui
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true
    envVars:
      PYTHON_VERSION: 3.10
