services:
  - type: web
    name: instagram-group-bot
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120 --workers 1 --bind 0.0.0.0:$PORT"
    envVars:
      PORT: "10000"
    autoDeploy: true
